name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        mkdir ./bin
        curl -LO https://github.com/instrumenta/conftest/releases/download/v0.19.0/conftest_0.19.0_Linux_x86_64.tar.gz \
          && tar xzf conftest_0.19.0_Linux_x86_64.tar.gz \
          && mv conftest ./bin
        curl -LO https://github.com/instrumenta/kubeval/releases/download/0.15.0/kubeval-linux-amd64.tar.gz \
          && tar xzf kubeval-linux-amd64.tar.gz \
          && sudo mv kubeval ./bin
        export PATH=$PATH:$(pwd)/bin
        make test

    - name: Build
      run: make build

    - name: Test Publish
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --snapshot --skip-publish --rm-dist
      env:
        CONFLINT_VERSION: "0.1.0"
